const fs = require('fs');
const path = require('path');
const packageJson = require('../package.json');

// Get version from package.json
const version = packageJson.version;

// Get current date/time
const buildDate = new Date().toISOString();

// Generate version info
const versionInfo = {
    version: version,
    buildDate: buildDate,
    buildTimestamp: Date.now()
};

// Create version.ts file
const versionContent = `// This file is auto-generated by generate-version.js
export const VERSION_INFO = ${JSON.stringify(versionInfo, null, 2)};
`;

// Ensure directory exists
const versionDir = path.join(__dirname, '..', 'nodes', 'Moodle');
if (!fs.existsSync(versionDir)) {
    fs.mkdirSync(versionDir, { recursive: true });
}

// Write version file
fs.writeFileSync(path.join(versionDir, 'version.ts'), versionContent);

console.log(`✅ Generated version.ts with version ${version} at ${buildDate}`);
